#!/bin/bash

if [[ -z "$1" || "$1" == "--help" ]]; then
    # provides help to the user
    echo "Usage: $0 <filename>"
    exit 1
fi

if [[ -f "$1" ]]; then
    echo "It's a file"
elif [[ -d "$1" ]]; then
    echo "It's a directory"
else
    echo "Not found: $1"
fi
