#!/bin/bash

print_numbered() {
	local items=("$@")
	local i=1
	for item in "${items[@]}"; do
		echo "$i. $item"
		((i++))
	done
}

tasks=("Buy milk" "Walk dog" "Write code")
print_numbered "${tasks[@]}"
