apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  labels:
    app: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mealie
  template:
    metadata:
      labels:
        pod: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.20.1
        volumeMounts:
        - name: mealie-pvc
          mountPath: /app/data
        ports:
        - containerPort: 9000
      volumes:
      - name: mealie-pvc
        persistentVolumeClaim:
          claimName: mealie-pvc
